#!/usr/bin/osascript
on checkit()
	
	set findcmd to do shell script "/usr/bin/mdfind kMDItemCFBundleIdentifier=com.oneidentity.scalus.macos | head -1"
	set cmdpath to findcmd & "/Contents/MacOS/scalus"
	set res to do shell script "test -f " & cmdpath & "; echo $?"
	set exitCode to res as number
	if (exitCode is not equal to 0) then
		display dialog "scalus was not found in path:" & cmdpath
	end if
	return cmdpath
end checkit

on open location theURL
	set cmdpath to checkit()
	if theUrl is not equal to "" then
	    do shell script cmdpath & " launch -u '" & theURL & "'"
    else
	    do shell script cmdpath
	end if
end open location

